version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "22:30"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    groups:
      github-actions-non-major:
        update-types:
          - "minor"
          - "patch"
      github-actions-major:
        update-types:
          - "major"
    labels:
      - "in progress"
      - "dependencies"
