# These are supported funding model platforms

github: Ludy87
custom:
  [
    "https://paypal.me/astragermany",
    "https://www.buymeacoffee.com/ludy87",
    "https://github.com/sponsors/Ludy87",
    "https://smile.amazon.de/registry/wishlist/2MX8QK8VE9MV1",
  ]
