name: Bandit Check

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/**"
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref_name || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  bandit:
    runs-on: "ubuntu-latest"
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Bandit Check (Python security linter)
        uses: jpetrucciani/bandit-check@0306d6e0f0ff600eebb8d92731fdce948d8b4c8e # master
        with:
          bandit_flags: "-s B105"
          path: "./custom_components/ipv64/"
