name: Validate with hassfest and HACS

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/**"
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref_name || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate_hacs:
    name: "HACS Validation"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: HACS Action
        uses: hacs/action@1ebf01c408f29afcb6406bd431bc98fd8cbb15aa # main
        with:
          category: "integration"
  validate_hassfest:
    name: "Hassfest Validation"
    runs-on: "ubuntu-latest"
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: home-assistant/actions/hassfest@e91ad1948e57189485b9c1ad608af0c303946f89 # master
